package slpl.syntax.lexical;

public enum TokenTypeClass {

    COMMENT,
    OPERATOR,
    BINARY_OPERATOR,
    UNARY_OPERATOR,
    ARITHMETIC_OPERATOR,
    LOGICAL_OPERATOR,
    RELATIONAL_OPERATOR,
    ASSIGNMENT_OPERATOR,
    LAYOUT,
    KEYWORD,
    VALUE,
    SYMBOL,
    BRACKET

}
